# Generated by Django 5.1.4 on 2025-01-25 04:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='No type', max_length=30)),
                ('name', models.CharField(default='No title', max_length=100)),
                ('desc', models.CharField(default='No description', max_length=10000)),
                ('analyst', models.CharField(default='Not assigned', max_length=100)),
                ('reviewed_by', models.CharField(default='Not assigned', max_length=100)),
                ('review_status', models.CharField(default='Not reviewed', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='open', max_length=10)),
                ('responder', models.CharField(default='', max_length=100)),
                ('submission_id', models.CharField(default='', max_length=100)),
                ('submission_date', models.DateField(default=datetime.date(2025, 1, 25))),
                ('department', models.CharField(default='', max_length=50)),
                ('items', models.CharField(default='', max_length=50)),
                ('price', models.FloatField(default=0.0)),
                ('variation', models.CharField(default='No variation provided', max_length=200)),
                ('notes', models.CharField(default='No notes provided', max_length=200)),
                ('quantity', models.IntegerField(default=0)),
                ('ship_to', models.CharField(default='', max_length=100)),
                ('shipping_address', models.CharField(blank=True, default='No shipping address provided', max_length=100)),
                ('hyperlink', models.CharField(default='', max_length=500)),
                ('tracking_url', models.CharField(default='No tracking url provided', max_length=500)),
                ('private_notes', models.CharField(default='', max_length=5000)),
            ],
        ),
    ]
