# Generated by Django 5.1.4 on 2025-02-05 13:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='submission_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
