# Generated by Django 5.1.4 on 2025-01-25 04:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='date',
            field=models.DateTimeField(default=datetime.date(2025, 1, 25)),
        ),
    ]
