# Generated by Django 5.1.4 on 2025-02-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_order_submission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='department',
            field=models.CharField(default='No department', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(default='No email', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='hyperlink',
            field=models.CharField(default='No hyperlink', max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.CharField(default='No items', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.CharField(default='No notes', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='private_notes',
            field=models.CharField(default='No private notes', max_length=5000),
        ),
        migrations.AlterField(
            model_name='order',
            name='responder',
            field=models.CharField(default='No username', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='ship_to',
            field=models.CharField(default='No shipping method', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(blank=True, default='No shipping address', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='submission_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_url',
            field=models.CharField(default='No tracking url', max_length=500),
        ),
    ]
