# Generated by Django 5.1.4 on 2025-01-27 05:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_incident_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='date',
            field=models.DateTimeField(default=datetime.date(2025, 1, 27)),
        ),
        migrations.AlterField(
            model_name='order',
            name='submission_date',
            field=models.DateField(default=datetime.date(2025, 1, 27)),
        ),
    ]
