# Generated by Django 5.1.4 on 2025-02-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_order_department_alter_order_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='variation',
            field=models.CharField(default='No variation', max_length=200),
        ),
    ]
