# Generated by Django 5.1.4 on 2025-01-30 13:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_incident_date_alter_order_submission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='submission_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
