# Generated by Django 5.1.4 on 2025-02-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_order_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.CharField(blank=True, default='No notes', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='variation',
            field=models.CharField(blank=True, default='No variation', max_length=200),
        ),
    ]
