# Generated by Django 5.1.4 on 2025-01-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_order_email_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='private_notes',
            field=models.CharField(default='No private notes', max_length=5000),
        ),
    ]
