# Generated by Django 5.1.4 on 2025-02-05 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_order_notes_alter_order_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='submission_date',
            field=models.DateField(default=datetime.date(2025, 2, 5)),
        ),
    ]
