# Generated by Django 5.1.4 on 2025-01-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_order_private_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_url',
            field=models.CharField(default='', max_length=500),
        ),
    ]
