# Generated by Django 5.1.4 on 2025-02-06 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_order_submission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='private_notes',
            field=models.CharField(blank='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='order',
            name='submission_date',
            field=models.DateField(default=datetime.date(2025, 2, 6)),
        ),
    ]
