# Generated by Django 5.1.4 on 2025-02-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_order_private_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='private_notes',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
