# Generated by Django 5.1.4 on 2025-02-26 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_order_private_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpensiveOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_id', models.IntegerField(default=-1)),
                ('purchase_order', models.CharField(max_length=300)),
                ('invoice', models.CharField(max_length=300)),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='submission_id',
            new_name='purchase_order',
        ),
        migrations.AlterField(
            model_name='order',
            name='submission_date',
            field=models.DateField(default=datetime.date(2025, 2, 26)),
        ),
    ]
