# Generated by Django 5.1.4 on 2025-02-05 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_application_apikeys'),
    ]

    operations = [
        migrations.DeleteModel(
            name='APIKeys',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
