# Generated by Django 5.1.4 on 2025-02-26 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_expensiveorder_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='purchase_order',
            new_name='submission_id',
        ),
    ]
