# Generated by Django 5.1.4 on 2025-02-27 05:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_purchase_order_order_submission_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='submission_date',
            field=models.DateField(default=datetime.date(2025, 2, 27)),
        ),
    ]
