# Generated by Django 5.1.4 on 2025-03-17 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_order_invoice_uploaded_alter_order_submission_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='location',
            field=models.CharField(default='Canada', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='submission_date',
            field=models.DateField(default=datetime.date(2025, 3, 17)),
        ),
    ]
